  
import { Country } from './County';

export const COUNTRY_LIST: Country[] = [
    { id: "FR", name: "France", code: "FR", flag: '' },
    { id: "BE", name: "Belgium", code: "BE", flag: '' },
    { id: "CA", name: "Canada", code: "CA", flag: '' },
    { id: "GB", name: "United Kingdom", code: "GB", flag: '' },
    { id: "US", name: "United States", code: "US", flag: '' },
    { id: "--", name: "------------", code: "-- ", flag: '' },
    { id: "AF", name: "Afghanistan", code: "AF", flag: '' },
    { id: "AX", name: "Aland Islands", code: "AX", flag: '' },
    { id: "AL", name: "Albania", code: "AL", flag: '' },
    { id: "DZ", name: "Algeria", code: "DZ", flag: '' },
    { id: "AS", name: "American Samoa", code: "AS", flag: '' },
    { id: "AD", name: "AndorrA", code: "AD", flag: '' },
    { id: "AO", name: "Angola", code: "AO", flag: '' },
    { id: "AI", name: "Anguilla", code: "AI", flag: '' },
    { id: "AQ", name: "Antarctica", code: "AQ", flag: '' },
    { id: "AG", name: "Antigua and Barbuda", code: "AG", flag: '' },
    { id: "AR", name: "Argentina", code: "AR", flag: '' },
    { id: "AM", name: "Armenia", code: "AM", flag: '' },
    { id: "AW", name: "Aruba", code: "AW", flag: '' },
    { id: "AU", name: "Australia", code: "AU", flag: '' },
    { id: "AT", name: "Austria", code: "AT", flag: '' },
    { id: "AZ", name: "Azerbaijan", code: "AZ", flag: '' },
    { id: "BS", name: "Bahamas", code: "BS", flag: '' },
    { id: "BH", name: "Bahrain", code: "BH", flag: '' },
    { id: "BD", name: "Bangladesh", code: "BD", flag: '' },
    { id: "BB", name: "Barbados", code: "BB", flag: '' },
    { id: "BY", name: "Belarus", code: "BY", flag: '' },
    { id: "BZ", name: "Belize", code: "BZ", flag: '' },
    { id: "BJ", name: "Benin", code: "BJ", flag: '' },
    { id: "BM", name: "Bermuda", code: "BM", flag: '' },
    { id: "BT", name: "Bhutan", code: "BT", flag: '' },
    { id: "BO", name: "Bolivia", code: "BO", flag: '' },
    { id: "BA", name: "Bosnia and Herzegovina", code: "BA", flag: '' },
    { id: "BW", name: "Botswana", code: "BW", flag: '' },
    { id: "BV", name: "Bouvet Island", code: "BV", flag: '' },
    { id: "BR", name: "Brazil", code: "BR", flag: '' },
    { id: "IO", name: "British Indian Ocean Territory", code: "IO", flag: '' },
    { id: "BN", name: "Brunei Darussalam", code: "BN", flag: '' },
    { id: "BG", name: "Bulgaria", code: "BG", flag: '' },
    { id: "BF", name: "Burkina Faso", code: "BF", flag: '' },
    { id: "BI", name: "Burundi", code: "BI", flag: '' },
    { id: "KH", name: "Cambodia", code: "KH", flag: '' },
    { id: "CM", name: "Cameroon", code: "CM", flag: '' },
    { id: "CV", name: "Cape Verde", code: "CV", flag: '' },
    { id: "KY", name: "Cayman Islands", code: "KY", flag: '' },
    { id: "CF", name: "Central African Republic", code: "CF", flag: '' },
    { id: "TD", name: "Chad", code: "TD", flag: '' },
    { id: "CL", name: "Chile", code: "CL", flag: '' },
    { id: "CN", name: "China", code: "CN", flag: '' },
    { id: "CX", name: "Christmas Island", code: "CX", flag: '' },
    { id: "CC", name: "Cocos (Keeling) Islands", code: "CC", flag: '' },
    { id: "CO", name: "Colombia", code: "CO", flag: '' },
    { id: "KM", name: "Comoros", code: "KM", flag: '' },
    { id: "CG", name: "Congo", code: "CG", flag: '' },
    { id: "CD", name: "Congo, The Democratic Republic of the", code: "CD", flag: '' },
    { id: "CK", name: "Cook Islands", code: "CK", flag: '' },
    { id: "CR", name: "Costa Rica", code: "CR", flag: '' },
    { id: "CI", name: "Cote D\'Ivoire", code: "CI", flag: '' },
    { id: "HR", name: "Croatia", code: "HR", flag: '' },
    { id: "CU", name: "Cuba", code: "CU", flag: '' },
    { id: "CY", name: "Cyprus", code: "CY", flag: '' },
    { id: "CZ", name: "Czech Republic", code: "CZ", flag: '' },
    { id: "DK", name: "Denmark", code: "DK", flag: '' },
    { id: "DJ", name: "Djibouti", code: "DJ", flag: '' },
    { id: "DM", name: "Dominica", code: "DM", flag: '' },
    { id: "DO", name: "Dominican Republic", code: "DO", flag: '' },
    { id: "EC", name: "Ecuador", code: "EC", flag: '' },
    { id: "EG", name: "Egypt", code: "EG", flag: '' },
    { id: "SV", name: "El Salvador", code: "SV", flag: '' },
    { id: "GQ", name: "Equatorial Guinea", code: "GQ", flag: '' },
    { id: "ER", name: "Eritrea", code: "ER", flag: '' },
    { id: "EE", name: "Estonia", code: "EE", flag: '' },
    { id: "ET", name: "Ethiopia", code: "ET", flag: '' },
    { id: "FK", name: "Falkland Islands (Malvinas", code: "FK", flag: '' },
    { id: "FO", name: "Faroe Islands", code: "FO", flag: '' },
    { id: "FJ", name: "Fiji", code: "FJ", flag: '' },
    { id: "FI", name: "Finland", code: "FI", flag: '' },
    { id: "GF", name: "French Guiana", code: "GF", flag: '' },
    { id: "PF", name: "French Polynesia", code: "PF", flag: '' },
    { id: "TF", name: "French Southern Territories", code: "TF", flag: '' },
    { id: "GA", name: "Gabon", code: "GA", flag: '' },
    { id: "GM", name: "Gambia", code: "GM", flag: '' },
    { id: "GE", name: "Georgia", code: "GE", flag: '' },
    { id: "DE", name: "Germany", code: "DE", flag: '' },
    { id: "GH", name: "Ghana", code: "GH", flag: '' },
    { id: "GI", name: "Gibraltar", code: "GI", flag: '' },
    { id: "GR", name: "Greece", code: "GR", flag: '' },
    { id: "GL", name: "Greenland", code: "GL", flag: '' },
    { id: "GD", name: "Grenada", code: "GD", flag: '' },
    { id: "GP", name: "Guadeloupe", code: "GP", flag: '' },
    { id: "GU", name: "Guam", code: "GU", flag: '' },
    { id: "GT", name: "Guatemala", code: "GT", flag: '' },
    { id: "GG", name: "Guernsey", code: "GG", flag: '' },
    { id: "GN", name: "Guinea", code: "GN", flag: '' },
    { id: "GW", name: "Guinea-Bissau", code: "GW", flag: '' },
    { id: "GY", name: "Guyana", code: "GY", flag: '' },
    { id: "HT", name: "Haiti", code: "HT", flag: '' },
    { id: "HM", name: "Heard Island and Mcdonald Islands", code: "HM", flag: '' },
    { id: "VA", name: "Holy See (Vatican City State", code: "VA", flag: '' },
    { id: "HN", name: "Honduras", code: "HN", flag: '' },
    { id: "HK", name: "Hong Kong", code: "HK", flag: '' },
    { id: "HU", name: "Hungary", code: "HU", flag: '' },
    { id: "IS", name: "Iceland", code: "IS", flag: '' },
    { id: "IN", name: "India", code: "IN", flag: '' },
    { id: "ID", name: "Indonesia", code: "ID", flag: '' },
    { id: "IR", name: "Iran, Islamic Republic Of", code: "IR", flag: '' },
    { id: "IQ", name: "Iraq", code: "IQ", flag: '' },
    { id: "IE", name: "Ireland", code: "IE", flag: '' },
    { id: "IM", name: "Isle of Man", code: "IM", flag: '' },
    { id: "IL", name: "Israel", code: "IL", flag: '' },
    { id: "IT", name: "Italy", code: "IT", flag: '' },
    { id: "JM", name: "Jamaica", code: "JM", flag: '' },
    { id: "JP", name: "Japan", code: "JP", flag: '' },
    { id: "JE", name: "Jersey", code: "JE", flag: '' },
    { id: "JO", name: "Jordan", code: "JO", flag: '' },
    { id: "KZ", name: "Kazakhstan", code: "KZ", flag: '' },
    { id: "KE", name: "Kenya", code: "KE", flag: '' },
    { id: "KI", name: "Kiribati", code: "KI", flag: '' },
    { id: "KP", name: "Korea, Democratic People\'S Republic of", code: "KP", flag: '' },
    { id: "KR", name: "Korea, Republic of", code: "KR", flag: '' },
    { id: "KW", name: "Kuwait", code: "KW", flag: '' },
    { id: "KG", name: "Kyrgyzstan", code: "KG", flag: '' },
    { id: "LA", name: "Lao People\'S Democratic Republic", code: "LA", flag: '' },
    { id: "LV", name: "Latvia", code: "LV", flag: '' },
    { id: "LB", name: "Lebanon", code: "LB", flag: '' },
    { id: "LS", name: "Lesotho", code: "LS", flag: '' },
    { id: "LR", name: "Liberia", code: "LR", flag: '' },
    { id: "LY", name: "Libyan Arab Jamahiriya", code: "LY", flag: '' },
    { id: "LI", name: "Liechtenstein", code: "LI", flag: '' },
    { id: "LT", name: "Lithuania", code: "LT", flag: '' },
    { id: "LU", name: "Luxembourg", code: "LU", flag: '' },
    { id: "MO", name: "Macao", code: "MO", flag: '' },
    { id: "MK", name: "Macedonia, The Former Yugoslav Republic of", code: "MK", flag: '' },
    { id: "MG", name: "Madagascar", code: "MG", flag: '' },
    { id: "MW", name: "Malawi", code: "MW", flag: '' },
    { id: "MY", name: "Malaysia", code: "MY", flag: '' },
    { id: "MV", name: "Maldives", code: "MV", flag: '' },
    { id: "ML", name: "Mali", code: "ML", flag: '' },
    { id: "MT", name: "Malta", code: "MT", flag: '' },
    { id: "MH", name: "Marshall Islands", code: "MH", flag: '' },
    { id: "MQ", name: "Martinique", code: "MQ", flag: '' },
    { id: "MR", name: "Mauritania", code: "MR", flag: '' },
    { id: "MU", name: "Mauritius", code: "MU", flag: '' },
    { id: "YT", name: "Mayotte", code: "YT", flag: '' },
    { id: "MX", name: "Mexico", code: "MX", flag: '' },
    { id: "FM", name: "Micronesia, Federated States of", code: "FM", flag: '' },
    { id: "MD", name: "Moldova, Republic of", code: "MD", flag: '' },
    { id: "MC", name: "Monaco", code: "MC", flag: '' },
    { id: "MN", name: "Mongolia", code: "MN", flag: '' },
    { id: "MS", name: "Montserrat", code: "MS", flag: '' },
    { id: "MA", name: "Morocco", code: "MA", flag: '' },
    { id: "MZ", name: "Mozambique", code: "MZ", flag: '' },
    { id: "MM", name: "Myanmar", code: "MM", flag: '' },
    { id: "NA", name: "Namibia", code: "NA", flag: '' },
    { id: "NR", name: "Nauru", code: "NR", flag: '' },
    { id: "NP", name: "Nepal", code: "NP", flag: '' },
    { id: "NL", name: "Netherlands", code: "NL", flag: '' },
    { id: "AN", name: "Netherlands Antilles", code: "AN", flag: '' },
    { id: "NC", name: "New Caledonia", code: "NC", flag: '' },
    { id: "NZ", name: "New Zealand", code: "NZ", flag: '' },
    { id: "NI", name: "Nicaragua", code: "NI", flag: '' },
    { id: "NE", name: "Niger", code: "NE", flag: '' },
    { id: "NG", name: "Nigeria", code: "NG", flag: '' },
    { id: "NU", name: "Niue", code: "NU", flag: '' },
    { id: "NF", name: "Norfolk Island", code: "NF", flag: '' },
    { id: "MP", name: "Northern Mariana Islands", code: "MP", flag: '' },
    { id: "NO", name: "Norway", code: "NO", flag: '' },
    { id: "OM", name: "Oman", code: "OM", flag: '' },
    { id: "PK", name: "Pakistan", code: "PK", flag: '' },
    { id: "PW", name: "Palau", code: "PW", flag: '' },
    { id: "PS", name: "Palestinian Territory, Occupied", code: "PS", flag: '' },
    { id: "PA", name: "Panama", code: "PA", flag: '' },
    { id: "PG", name: "Papua New Guinea", code: "PG", flag: '' },
    { id: "PY", name: "Paraguay", code: "PY", flag: '' },
    { id: "PE", name: "Peru", code: "PE", flag: '' },
    { id: "PH", name: "Philippines", code: "PH", flag: '' },
    { id: "PN", name: "Pitcairn", code: "PN", flag: '' },
    { id: "PL", name: "Poland", code: "PL", flag: '' },
    { id: "PT", name: "Portugal", code: "PT", flag: '' },
    { id: "PR", name: "Puerto Rico", code: "PR", flag: '' },
    { id: "QA", name: "Qatar", code: "QA", flag: '' },
    { id: "RE", name: "Reunion", code: "RE", flag: '' },
    { id: "RO", name: "Romania", code: "RO", flag: '' },
    { id: "RU", name: "Russian Federation", code: "RU", flag: '' },
    { id: "RW", name: "RWANDA", code: "RW", flag: '' },
    { id: "SH", name: "Saint Helena", code: "SH", flag: '' },
    { id: "KN", name: "Saint Kitts and Nevis", code: "KN", flag: '' },
    { id: "LC", name: "Saint Lucia", code: "LC", flag: '' },
    { id: "PM", name: "Saint Pierre and Miquelon", code: "PM", flag: '' },
    { id: "VC", name: "Saint Vincent and the Grenadines", code: "VC", flag: '' },
    { id: "WS", name: "Samoa", code: "WS", flag: '' },
    { id: "SM", name: "San Marino", code: "SM", flag: '' },
    { id: "ST", name: "Sao Tome and Principe", code: "ST", flag: '' },
    { id: "SA", name: "Saudi Arabia", code: "SA", flag: '' },
    { id: "SN", name: "Senegal", code: "SN", flag: '' },
    { id: "CS", name: "Serbia and Montenegro", code: "CS", flag: '' },
    { id: "SC", name: "Seychelles", code: "SC", flag: '' },
    { id: "SL", name: "Sierra Leone", code: "SL", flag: '' },
    { id: "SG", name: "Singapore", code: "SG", flag: '' },
    { id: "SK", name: "Slovakia", code: "SK", flag: '' },
    { id: "SI", name: "Slovenia", code: "SI", flag: '' },
    { id: "SB", name: "Solomon Islands", code: "SB", flag: '' },
    { id: "SO", name: "Somalia", code: "SO", flag: '' },
    { id: "ZA", name: "South Africa", code: "ZA", flag: '' },
    { id: "GS", name: "South Georgia and the South Sandwich Islands", code: "GS", flag: '' },
    { id: "ES", name: "Spain", code: "ES", flag: '' },
    { id: "LK", name: "Sri Lanka", code: "LK", flag: '' },
    { id: "SD", name: "Sudan", code: "SD", flag: '' },
    { id: "SR", name: "Suriname", code: "SR", flag: '' },
    { id: "SJ", name: "Svalbard and Jan Mayen", code: "SJ", flag: '' },
    { id: "SZ", name: "Swaziland", code: "SZ", flag: '' },
    { id: "SE", name: "Sweden", code: "SE", flag: '' },
    { id: "CH", name: "Switzerland", code: "CH", flag: '' },
    { id: "SY", name: "Syrian Arab Republic", code: "SY", flag: '' },
    { id: "TW", name: "Taiwan, Province of China", code: "TW", flag: '' },
    { id: "TJ", name: "Tajikistan", code: "TJ", flag: '' },
    { id: "TZ", name: "Tanzania, United Republic of", code: "TZ", flag: '' },
    { id: "TH", name: "Thailand", code: "TH", flag: '' },
    { id: "TL", name: "Timor-Leste", code: "TL", flag: '' },
    { id: "TG", name: "Togo", code: "TG", flag: '' },
    { id: "TK", name: "Tokelau", code: "TK", flag: '' },
    { id: "TO", name: "Tonga", code: "TO", flag: '' },
    { id: "TT", name: "Trinidad and Tobago", code: "TT", flag: '' },
    { id: "TN", name: "Tunisia", code: "TN", flag: '' },
    { id: "TR", name: "Turkey", code: "TR", flag: '' },
    { id: "TM", name: "Turkmenistan", code: "TM", flag: '' },
    { id: "TC", name: "Turks and Caicos Islands", code: "TC", flag: '' },
    { id: "TV", name: "Tuvalu", code: "TV", flag: '' },
    { id: "UG", name: "Uganda", code: "UG", flag: '' },
    { id: "UA", name: "Ukraine", code: "UA", flag: '' },
    { id: "AE", name: "United Arab Emirates", code: "AE", flag: '' },
    { id: "UM", name: "United States Minor Outlying Islands", code: "UM", flag: '' },
    { id: "UY", name: "Uruguay", code: "UY", flag: '' },
    { id: "UZ", name: "Uzbekistan", code: "UZ", flag: '' },
    { id: "VU", name: "Vanuatu", code: "VU", flag: '' },
    { id: "VE", name: "Venezuela", code: "VE", flag: '' },
    { id: "VN", name: "Viet Nam", code: "VN", flag: '' },
    { id: "VG", name: "Virgin Islands, British", code: "VG", flag: '' },
    { id: "VI", name: "Virgin Islands, U.S", code: "VI", flag: '' },
    { id: "WF", name: "Wallis and Futuna", code: "WF", flag: '' },
    { id: "EH", name: "Western Sahara", code: "EH", flag: '' },
    { id: "YE", name: "Yemen", code: "YE", flag: '' },
    { id: "ZM", name: "Zambia", code: "ZM", flag: '' },
    { id: "ZW", name: "Zimbabwe", code: "ZW", flag: '' },
]; 